// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: sensors/sensors.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SensorService_StreamSensorData_FullMethodName = "/api.SensorService/StreamSensorData"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	StreamSensorData(ctx context.Context, opts ...grpc.CallOption) (SensorService_StreamSensorDataClient, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) StreamSensorData(ctx context.Context, opts ...grpc.CallOption) (SensorService_StreamSensorDataClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], SensorService_StreamSensorData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sensorServiceStreamSensorDataClient{ClientStream: stream}
	return x, nil
}

type SensorService_StreamSensorDataClient interface {
	Send(*SensorData) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type sensorServiceStreamSensorDataClient struct {
	grpc.ClientStream
}

func (x *sensorServiceStreamSensorDataClient) Send(m *SensorData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorServiceStreamSensorDataClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility
type SensorServiceServer interface {
	StreamSensorData(SensorService_StreamSensorDataServer) error
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServiceServer struct {
}

func (UnimplementedSensorServiceServer) StreamSensorData(SensorService_StreamSensorDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSensorData not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_StreamSensorData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).StreamSensorData(&sensorServiceStreamSensorDataServer{ServerStream: stream})
}

type SensorService_StreamSensorDataServer interface {
	SendAndClose(*Empty) error
	Recv() (*SensorData, error)
	grpc.ServerStream
}

type sensorServiceStreamSensorDataServer struct {
	grpc.ServerStream
}

func (x *sensorServiceStreamSensorDataServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorServiceStreamSensorDataServer) Recv() (*SensorData, error) {
	m := new(SensorData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSensorData",
			Handler:       _SensorService_StreamSensorData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sensors/sensors.proto",
}
